In [1]:
import pandas as pd

# Load the data from the CSV file
file_path = 'supplemental_clinical_data.csv'
data = pd.read_csv(file_path)

# Display the data
data

,visit_id,patient_id,visit_month,updrs_1,updrs_2,updrs_3,updrs_4,upd23b_clinical_state_on_medication
0,35_0,35,0,5.0,3.0,16.0,0.0,NaN
1,35_36,35,36,6.0,4.0,20.0,0.0,NaN
2,75_0,75,0,4.0,6.0,26.0,0.0,NaN
3,75_36,75,36,1.0,8.0,38.0,0.0,On
4,155_0,155,0,NaN,NaN,0.0,NaN,NaN
...,...,...,...,...,...,...,...,...
2218,65382_0,65382,0,NaN,NaN,0.0,NaN,NaN
2219,65405_0,65405,0,5.0,16.0,31.0,0.0,NaN
2220,65405_5,65405,5,NaN,NaN,57.0,NaN,NaN
2221,65530_0,65530,0,10.0,6.0,24.0,0.0,NaN
2222,65530_36,65530,36,8.0,4.0,15.0,4.0,On

In [2]:
import pandas as pd
import numpy as np
import statsmodels.api as sm
import matplotlib.pyplot as plt

def forecast_statsmodels(data, forecast_periods=10):
    model = sm.tsa.ARIMA(data, order=(1, 1, 1))  # Ajusta el modelo ARIMA según tu serie temporal
    results = model.fit()

    forecast = results.get_forecast(steps=forecast_periods)
    forecast_index = pd.date_range(start=data.index[-1], periods=forecast_periods + 1, freq='M')[1:]
    
    forecast_mean = forecast.predicted_mean
    forecast_ci = forecast.conf_int()

    plt.figure(figsize=(10, 6))
    plt.plot(data.index, data, label='Actual')
    plt.plot(forecast_index, forecast_mean, color='red', label='Forecast')
    plt.fill_between(forecast_index, forecast_ci.iloc[:, 0], forecast_ci.iloc[:, 1], color='red', alpha=0.2)
    plt.legend()
    plt.show()

# Uso de ejemplo:
# Supongamos que 'tu_data' es tu serie temporal (puedes cargarla desde un archivo CSV o DataFrame)
# forecast_statsmodels(tu_data)

In [9]:
import pandas as pd
import numpy as np
import statsmodels.api as sm
import matplotlib.pyplot as plt

# Cargar datos desde el archivo CSV
file_path = 'supplemental_clinical_data.csv'
data = pd.read_csv(file_path)

# Asumiendo que estás trabajando con una serie temporal específica, por ejemplo, 'updrs_1'
serie_temporal = data['updrs_1'].dropna()

# Pronóstico con statsmodels
def forecast_statsmodels(data, forecast_periods=10):
    model = sm.tsa.ARIMA(data, order=(1, 1, 1))
    results = model.fit()

    forecast = results.get_forecast(steps=forecast_periods)
    forecast_index = pd.date_range(start=data.index[-1], periods=forecast_periods + 1, freq='M')[1:]
    
    forecast_mean = forecast.predicted_mean
    forecast_ci = forecast.conf_int()

    plt.figure(figsize=(10, 6))
    plt.plot(data.index, data, label='Actual')
    plt.plot(forecast_index, forecast_mean, color='red', label='Forecast')
    plt.fill_between(forecast_index, forecast_ci.iloc[:, 0], forecast_ci.iloc[:, 1], color='red', alpha=0.2)
    plt.legend()
    plt.show()