In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns

In [8]:
Peptides_data = pd.read_csv('train_peptides.csv')
Proteins_data = pd.read_csv('train_proteins.csv')
supplemental_clinical_data = pd.read_csv('supplemental_clinical_data.csv')
train_clinical_data = pd.read_csv('train_clinical_data.csv')

Proteins_data

         visit_id  visit_month  patient_id UniProt       NPX
0            55_0            0          55  O00391   11254.3
1            55_0            0          55  O00533  732430.0
2            55_0            0          55  O00584   39585.8
3            55_0            0          55  O14498   41526.9
4            55_0            0          55  O14773   31238.0
...           ...          ...         ...     ...       ...
232736  58648_108          108       58648  Q9UBX5   27387.8
232737  58648_108          108       58648  Q9UHG2  369437.0
232738  58648_108          108       58648  Q9UKV8  105830.0
232739  58648_108          108       58648  Q9Y646   21257.6
232740  58648_108          108       58648  Q9Y6R7   17953.1

[232741 rows x 5 columns]

In [7]:
#print(Proteins_data.head())
#print(Peptides_data.head())
 
Proteins_data = [Peptides_data]
Proteins_data

[         visit_id  visit_month  patient_id UniProt  \
 0            55_0            0          55  O00391
 1            55_0            0          55  O00533
 2            55_0            0          55  O00533
 3            55_0            0          55  O00533
 4            55_0            0          55  O00533
 ...           ...          ...         ...     ...
 981829  58648_108          108       58648  Q9UHG2
 981830  58648_108          108       58648  Q9UKV8
 981831  58648_108          108       58648  Q9Y646
 981832  58648_108          108       58648  Q9Y6R7
 981833  58648_108          108       58648  Q9Y6R7

                                        Peptide  PeptideAbundance
 0                                NEQEQPLGQWHLS          11254.30
 1                                  GNPEPTFSWTK         102060.00
 2                              IEIPSSVQQVPTIIK         174185.00
 3       KPQSAVYSTGSNGILLC(UniMod_4)EAEGEPQPTIK          27278.90
 4                                 SMEQNGPGLEYR          30838.70
 ...                                        ...               ...
 981829                         ILAGSADSEGVAAPR         202820.00
 981830                           SGNIPAGTTVDTK         105830.00
 981831                             LALLVDTVGPR          21257.60
 981832        AGC(UniMod_4)VAESTAVC(UniMod_4)R           5127.26
 981833                          GATTSPGVYELSSR          12825.90

 [981834 rows x 6 columns]]